apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    run: broker
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: broker
